### ISSUE TITLE
Refactor Questionnaire View

### ISSUE THREAD

**Issue by MatthewBotha** [teampinocchio/pinocchio#51]
teamMembers can be a list of users, not teamDetail objects. This has to change in the questionnaire view, the questionnaire_preview view as well as all question templates (.html)

**Comment by Jason-vh** [comment]
The reason I made it TeamDetail objects instead of Users is because I didn't want to have student numbers (which are the primary keys of User) being passed around in JavaScript. 
I can change it to Users, but I just need to find another way to uniquely identify each user then.

**Comment by RagingGrim** [comment]
How about generating an md5 hash for every student number?

**Comment by vpieterse** [comment]
Why?

**Comment by Jason-vh** [comment]
Because I'd rather not have student numbers passed around in the JavaScript. I like the idea of hashing them, but I need to do it in some way that allows me to convert them back server-side upon saving (Which isn't doable with hashes)
For initial deployment I am just using student numbers.

**Comment by vpieterse** [comment]
It seems if we need the system user ID (something identifying the user object) to identify users rather than using their user names (which is in our case the student numbers).  No hashing is needed, we need change all communication involving user objects not to use the user name, but rather the user object ID.

**Comment by Jason-vh** [comment]
I'm going to leave this as-is for now, until it can be discussed in detail on Thursday

**Comment by Jason-vh** [comment]
This has been sorted with the move to userIDs instead of student numbers.
