### ISSUE TITLE
Implement Maintain Rounds

### ISSUE THREAD

**Issue by mewh** [teampinocchio/pinocchio#8]
As shown in the interface branch. @Constancon Please try implement this. Just ask here if you have any questions.
- [ ] Interface with database
- [ ] Change Maintain to Teams. Clicking on this should take you to the team builder
- [ ] Remove accept edit button. Should save on losing focus
- [ ] Sortable
- [ ] Assign a questionnaire to a round

**Comment by vpieterse** [comment]
I again thought about the deletion of rounds. I now think it should be possible to delete a round. If there are no teams or answers related to it, it should be deleted without any problems. If, however, there are teams and answers associated with it, all should be deleted with double confirmation.

**Comment by MatthiasHarvey** [comment]
That sounds like a good way to do it.
